import type { Category, Product, Store, Testimonial } from "./types";

export const BRAND = {
  name: "Thaaza",
  tagline: "Live-cut. Always fresh.",
  city: "Hyderabad",
  phone: "+91 90000 00000",
  email: "hello@thaaza.in",
  themeColor: "#8B1E3F",
};

const IMG = {
  maleGoat: "/images/products/male-goat.png",
  maleSheep: "/images/products/male-sheep.png",
  goatCurry: "/images/products/goat-curry.png",
  goatBoneless: "/images/products/goat-boneless.png",
  keema: "/images/products/keema.png",
  paya: "/images/products/paya.png",
  sheep: "/images/products/sheep-mutton.png",
  sheepBoneless: "/images/products/sheep-boneless.png",
  boilerHens: "/images/products/boiler-hens.png",
  chickenCurrySmall: "/images/products/chicken-curry-small.png",
  chickenBiryaniMedium: "/images/products/chicken-biryani-medium.png",
  chickenBoneless: "/images/products/chicken-boneless.png",
  chickenBreast: "/images/products/chicken-breast.png",
  chickenLegs: "/images/products/chicken-legs.png",
  chickenWings: "/images/products/chicken-wings.png",
  countryChicken:
    "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80",
  fish: "/images/products/raw-fish.png",
  prawnsLarge: "/images/products/prawns-large.png",
  prawnsMedium: "/images/products/prawns-medium.png",
  prawnsSmall: "/images/products/prawns-small.png",
  whiteEggs: "/images/products/white-eggs.png",
  brownEggs: "/images/products/brown-eggs.png",
  storeMadhapur: "/images/stores/madhapur.png",
  storeKukatpally: "/images/stores/kukatpally.png",
  storeLbNagar: "/images/stores/lbnagar.png",
};

export const categories: Category[] = [
  {
    id: "goat",
    name: "Goat (Meka Pothu)",
    slug: "goat",
    description: "Male goat, live-cut — curry, boneless, keema & paya bones.",
    image: IMG.maleGoat,
  },
  {
    id: "sheep",
    name: "Sheep (Pottelu)",
    slug: "sheep",
    description: "Male sheep, live-cut — curry, boneless, keema & paya bones.",
    image: IMG.maleSheep,
  },
  {
    id: "chicken",
    name: "Boiler Chicken",
    slug: "chicken",
    description: "Boiler chicken — curry, biryani, boneless, breasts, legs & wings.",
    image: IMG.boilerHens,
  },
  {
    id: "country-chicken",
    name: "Country Chicken",
    slug: "country-chicken",
    description: "Country chicken — richer flavour, slower cook.",
    image: IMG.countryChicken,
  },
  {
    id: "white-eggs",
    name: "White Eggs",
    slug: "white-eggs",
    description: "Farm-fresh white eggs — packs of 6, 12, 30 or custom count.",
    image: IMG.whiteEggs,
  },
  {
    id: "brown-eggs",
    name: "Brown Eggs",
    slug: "brown-eggs",
    description: "Brown eggs — packs of 6, 12, 30 or custom count.",
    image: IMG.brownEggs,
  },
  {
    id: "fish",
    name: "Freshwater Fish",
    slug: "fish",
    description: "Freshwater fish — whole or cleaned, cut the way you like.",
    image: IMG.fish,
  },
  {
    id: "prawns",
    name: "Prawns",
    slug: "prawns",
    description: "Fresh prawns — large, medium and small.",
    image: IMG.prawnsLarge,
  },
];

export const products: Product[] = [
  // Goat
  {
    id: "goat-curry",
    slug: "goat-curry-cut",
    name: "Goat — Curry Cut",
    categoryId: "goat",
    cut: "Curry cut",
    description:
      "Bone-in curry pieces from live goat. Ideal for Hyderabadi dum & home-style curries. Cut fresh after you order.",
    priceKey: "goatCurryPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.goatCurry,
    featured: true,
    tags: ["Live-cut", "Bone-in"],
  },
  {
    id: "goat-boneless",
    slug: "goat-boneless",
    name: "Goat — Boneless",
    categoryId: "goat",
    cut: "Boneless",
    description:
      "Clean boneless goat meat for fry, gravy or kebab. Cut from the same live animal you select.",
    priceKey: "goatBonelessPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.goatBoneless,
    tags: ["Boneless"],
  },
  {
    id: "goat-keema",
    slug: "goat-keema",
    name: "Goat — Keema",
    categoryId: "goat",
    cut: "Keema",
    description:
      "Freshly minced goat keema. Freshly minced at the store after live cut — never pre-packed mince.",
    priceKey: "goatKeemaPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.keema,
    tags: ["Minced"],
  },
  {
    id: "goat-paya",
    slug: "goat-paya",
    name: "Goat — Paya Bones",
    categoryId: "goat",
    cut: "Paya Bones",
    description:
      "Goat trotters cleaned and ready for slow-cooked paya. Available while stock lasts each morning.",
    priceKey: "goatPayaPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.5,
    image: IMG.paya,
    tags: ["Specialty"],
  },
  // Sheep
  {
    id: "sheep-curry",
    slug: "sheep-curry-cut",
    name: "Sheep — Curry Cut",
    categoryId: "sheep",
    cut: "Curry cut",
    description:
      "Live-cut sheep (mutton) curry pieces. Milder flavour than goat, perfect for everyday curries.",
    priceKey: "sheepCurryPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.sheep,
    featured: true,
    tags: ["Live-cut"],
  },
  {
    id: "sheep-boneless",
    slug: "sheep-boneless",
    name: "Sheep — Boneless",
    categoryId: "sheep",
    cut: "Boneless",
    description: "Boneless mutton for fry, stew or seekh. Cut to order.",
    priceKey: "sheepBonelessPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.sheepBoneless,
  },
  {
    id: "sheep-keema",
    slug: "sheep-keema",
    name: "Sheep — Keema",
    categoryId: "sheep",
    cut: "Keema",
    description: "Fresh sheep keema, minced at the counter after live cut.",
    priceKey: "sheepKeemaPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.keema,
  },
  {
    id: "sheep-paya",
    slug: "sheep-paya",
    name: "Sheep — Paya Bones",
    categoryId: "sheep",
    cut: "Paya Bones",
    description: "Sheep paya cleaned and packed for weekend nihari or soup.",
    priceKey: "sheepPayaPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.5,
    image: IMG.paya,
  },
  // Boiler chicken
  {
    id: "boiler-curry",
    slug: "boiler-chicken-curry-cut",
    name: "Boiler Chicken — Curry Cut",
    categoryId: "chicken",
    cut: "Curry cut",
    description:
      "Boiler chicken curry cut with skin as preferred. Daily fresh stock.",
    priceKey: "boilerCurryPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.chickenCurrySmall,
    featured: true,
    tags: ["Daily fresh"],
  },
  {
    id: "boiler-biryani",
    slug: "boiler-chicken-biryani-cut",
    name: "Boiler Chicken — Biryani Cut",
    categoryId: "chicken",
    cut: "Biryani cut",
    description: "Boiler chicken cut for biryani pots — bone-in pieces sized for dum.",
    priceKey: "boilerBiryaniPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.chickenBiryaniMedium,
    tags: ["Biryani"],
  },
  {
    id: "boiler-boneless",
    slug: "boiler-chicken-boneless",
    name: "Boiler Chicken — Boneless",
    categoryId: "chicken",
    cut: "Boneless",
    description: "Boneless boiler chicken for grill, curry or meal prep.",
    priceKey: "boilerBonelessPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.chickenBoneless,
  },
  {
    id: "boiler-breast",
    slug: "boiler-chicken-breasts",
    name: "Boiler Chicken — Breasts",
    categoryId: "chicken",
    cut: "Breasts",
    description: "Chicken breast pieces — lean and ready for grill or gravy.",
    priceKey: "boilerBreastPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.chickenBreast,
  },
  {
    id: "boiler-leg",
    slug: "boiler-chicken-leg-pieces",
    name: "Boiler Chicken — Leg Pieces",
    categoryId: "chicken",
    cut: "Leg Pieces",
    description: "Bone-in leg pieces for fry, curry or roast.",
    priceKey: "boilerLegPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.chickenLegs,
  },
  {
    id: "boiler-wings",
    slug: "boiler-chicken-wings",
    name: "Boiler Chicken — Wings",
    categoryId: "chicken",
    cut: "Wings",
    description: "Chicken wings for snack fry or BBQ marinade.",
    priceKey: "boilerWingsPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.chickenWings,
  },
  // Country chicken
  {
    id: "country-curry",
    slug: "country-chicken-curry-cut",
    name: "Country Chicken — Curry Cut",
    categoryId: "country-chicken",
    cut: "Curry cut",
    description:
      "Country chicken curry cut. Firmer meat, deeper flavour — best slow-cooked.",
    priceKey: "countryCurryPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.countryChicken,
    featured: true,
    tags: ["Country"],
  },
  {
    id: "country-boneless",
    slug: "country-chicken-boneless",
    name: "Country Chicken — Boneless",
    categoryId: "country-chicken",
    cut: "Boneless",
    description: "Boneless country chicken for fry or gravy.",
    priceKey: "countryBonelessPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.countryChicken,
  },
  // White eggs
  {
    id: "white-eggs-6",
    slug: "white-eggs-6",
    name: "White Eggs (6)",
    categoryId: "white-eggs",
    cut: "Pack of 6",
    description: "Farm-fresh white eggs — pack of 6.",
    priceKey: "whiteEggs6",
    unit: "eggs",
    minQty: 6,
    step: 1,
    image: IMG.whiteEggs,
    featured: true,
    tags: ["White"],
  },
  {
    id: "white-eggs-12",
    slug: "white-eggs-12",
    name: "White Eggs (12)",
    categoryId: "white-eggs",
    cut: "Pack of 12",
    description: "Farm-fresh white eggs — pack of 12.",
    priceKey: "whiteEggs12",
    unit: "eggs",
    minQty: 12,
    step: 1,
    image: IMG.whiteEggs,
    tags: ["White"],
  },
  {
    id: "white-eggs-30",
    slug: "white-eggs-30",
    name: "White Eggs (30)",
    categoryId: "white-eggs",
    cut: "Pack of 30",
    description: "Farm-fresh white eggs — tray of 30.",
    priceKey: "whiteEggs30",
    unit: "eggs",
    minQty: 30,
    step: 1,
    image: IMG.whiteEggs,
    tags: ["White"],
  },
  {
    id: "white-eggs-custom",
    slug: "white-eggs-custom",
    name: "White Eggs — Custom",
    categoryId: "white-eggs",
    cut: "Custom",
    description: "Choose any egg count. Price updates at the per-egg rate.",
    priceKey: "whiteEggsPerEgg",
    unit: "eggs",
    minQty: 1,
    step: 1,
    image: IMG.whiteEggs,
    tags: ["White", "Custom"],
  },
  // Brown eggs
  {
    id: "brown-eggs-6",
    slug: "brown-eggs-6",
    name: "Brown Eggs (6)",
    categoryId: "brown-eggs",
    cut: "Pack of 6",
    description: "Brown eggs — pack of 6.",
    priceKey: "brownEggs6",
    unit: "eggs",
    minQty: 6,
    step: 1,
    image: IMG.brownEggs,
    featured: true,
    tags: ["Brown"],
  },
  {
    id: "brown-eggs-12",
    slug: "brown-eggs-12",
    name: "Brown Eggs (12)",
    categoryId: "brown-eggs",
    cut: "Pack of 12",
    description: "Brown eggs — pack of 12.",
    priceKey: "brownEggs12",
    unit: "eggs",
    minQty: 12,
    step: 1,
    image: IMG.brownEggs,
    tags: ["Brown"],
  },
  {
    id: "brown-eggs-30",
    slug: "brown-eggs-30",
    name: "Brown Eggs (30)",
    categoryId: "brown-eggs",
    cut: "Pack of 30",
    description: "Brown eggs — tray of 30.",
    priceKey: "brownEggs30",
    unit: "eggs",
    minQty: 30,
    step: 1,
    image: IMG.brownEggs,
    tags: ["Brown"],
  },
  {
    id: "brown-eggs-custom",
    slug: "brown-eggs-custom",
    name: "Brown Eggs — Custom",
    categoryId: "brown-eggs",
    cut: "Custom",
    description: "Choose any egg count. Price updates at the per-egg rate.",
    priceKey: "brownEggsPerEgg",
    unit: "eggs",
    minQty: 1,
    step: 1,
    image: IMG.brownEggs,
    tags: ["Brown", "Custom"],
  },
  // Fish — one product
  {
    id: "fish-freshwater",
    slug: "freshwater-fish-whole-clean",
    name: "Freshwater Fish — Whole/Clean",
    categoryId: "fish",
    cut: "Whole/Clean",
    description:
      "Freshwater fish, whole or cleaned. Ask for curry pieces or fry cuts at the store.",
    priceKey: "fishPerKg",
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.fish,
    featured: true,
    tags: ["Freshwater"],
  },
  // Prawns
  {
    id: "prawns-large",
    slug: "prawns-large",
    name: "Large Prawns",
    categoryId: "prawns",
    cut: "Large",
    description: "Large prawns — cleaned or with shell on request.",
    priceKey: "prawnsLargePerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.prawnsLarge,
    featured: true,
    tags: ["Large"],
  },
  {
    id: "prawns-medium",
    slug: "prawns-medium",
    name: "Medium Prawns",
    categoryId: "prawns",
    cut: "Medium",
    description: "Medium prawns for fry, gravy or biryani.",
    priceKey: "prawnsMediumPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.prawnsMedium,
    tags: ["Medium"],
  },
  {
    id: "prawns-small",
    slug: "prawns-small",
    name: "Small Prawns",
    categoryId: "prawns",
    cut: "Small",
    description: "Small prawns — great for fry and everyday curries.",
    priceKey: "prawnsSmallPerKg",
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.prawnsSmall,
    tags: ["Small"],
  },
];

export const stores: Store[] = [
  {
    id: "madhapur",
    name: "Thaaza Madhapur",
    area: "Madhapur",
    address: "Near Ayyappa Society, Madhapur, Hyderabad 500081",
    phone: "+91 90000 11111",
    hours: "6:30 AM – 9:30 PM",
    lat: 17.4484,
    lng: 78.3908,
    image: IMG.storeMadhapur,
    specialties: ["Goat & sheep live-cut", "Biryani cuts", "Same-day delivery"],
  },
  {
    id: "kukatpally",
    name: "Thaaza Kukatpally",
    area: "Kukatpally",
    address: "KPHB Main Road, Kukatpally, Hyderabad 500072",
    phone: "+91 90000 22222",
    hours: "6:30 AM – 9:30 PM",
    lat: 17.4948,
    lng: 78.3996,
    image: IMG.storeKukatpally,
    specialties: ["Country chicken", "Fish & prawns", "Morning stock"],
  },
  {
    id: "lb-nagar",
    name: "Thaaza LB Nagar",
    area: "LB Nagar",
    address: "Near Ring Road, LB Nagar, Hyderabad 500074",
    phone: "+91 90000 33333",
    hours: "6:30 AM – 9:00 PM",
    lat: 17.3457,
    lng: 78.5522,
    image: IMG.storeLbNagar,
    specialties: ["Family packs", "Egg trays", "Takeaway rush hours"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sravanthi R.",
    area: "Madhapur",
    text: "Finally a shop where I can see the animal before they cut. Biryani cut for Sunday dum is consistent — no surprises like pre-packed dead stock.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Mohammed Irfan",
    area: "Tolichowki",
    text: "Ordered goat keema for evening. They minced after cutting, packed properly, and delivery reached before Maghrib. Proper Hyderabad style.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Lakshmi Devi",
    area: "Kukatpally",
    text: "Country chicken curry cut was fresh — not soft packed chicken. My mother-in-law noticed the difference immediately.",
    rating: 5,
  },
  {
    id: "t4",
    name: "Pradeep Kumar",
    area: "LB Nagar",
    text: "Visit store mode is useful. I pick the bird, they cut while I wait. Bill has GST breakup — clear and professional.",
    rating: 4,
  },
];

export const DELIVERY_FEE = 49;
export const GST_RATE = 0.05; // 5% demo GST on meat/fish for bill display
export const FREE_DELIVERY_ABOVE = 999;

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug || c.id === slug);
}

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug || p.id === slug);
}

export function getStore(id: string) {
  return stores.find((s) => s.id === id);
}

export function getProductsByCategory(categoryId: string) {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}

/** Resolve egg pack product id for a category + count (6/12/30), else custom. */
export function getEggProductId(
  categoryId: "white-eggs" | "brown-eggs",
  count: number
): string {
  const prefix = categoryId === "white-eggs" ? "white-eggs" : "brown-eggs";
  if (count === 6) return `${prefix}-6`;
  if (count === 12) return `${prefix}-12`;
  if (count === 30) return `${prefix}-30`;
  return `${prefix}-custom`;
}

export function isCustomEggProduct(product: { id: string; cut?: string }): boolean {
  return product.id.endsWith("-custom") || product.cut === "Custom";
}
