import type { Category, Product, Store, Testimonial } from "./types";

export const BRAND = {
  name: "Thaaza",
  tagline: "Live-cut. Always fresh.",
  telugu: "తాజా మాంసం",
  city: "Hyderabad",
  phone: "+91 90000 00000",
  email: "hello@thaaza.in",
  themeColor: "#8B1E3F",
};

const IMG = {
  goat: "/images/products/goat-curry.png",
  sheep: "/images/products/sheep-mutton.png",
  fish: "/images/products/raw-fish.png",
  prawns: "/images/products/prawns.png",
  whiteEggs: "/images/products/white-eggs.png",
  brownEggs: "/images/products/brown-eggs.png",
  chicken: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800&q=80",
  countryChicken: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80",
  countryWhole: "https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=800&q=80",
  storeMadhapur: "/images/stores/madhapur.png",
  storeKukatpally: "/images/stores/kukatpally.png",
  storeLbNagar: "/images/stores/lbnagar.png",
};

export const categories: Category[] = [
  {
    id: "goat",
    name: "Male Goat",
    nameTe: "మేక",
    slug: "goat",
    description: "Live-cut male goat — curry, biryani, boneless, keema & paya.",
    image: IMG.goat,
  },
  {
    id: "sheep",
    name: "Male Sheep",
    nameTe: "గొర్రె",
    slug: "sheep",
    description: "Fresh mutton from live male sheep, cut to your preference.",
    image: IMG.sheep,
  },
  {
    id: "chicken",
    name: "Chicken Broiler",
    nameTe: "చికెన్",
    slug: "chicken",
    description: "White broiler (40–60 day) — curry cut, boneless & whole.",
    image: IMG.chicken,
  },
  {
    id: "country-chicken",
    name: "Country Chicken",
    nameTe: "నాటు కోడి",
    slug: "country-chicken",
    description: "Brown / country chicken — richer flavour, slower cook.",
    image: IMG.countryChicken,
  },
  {
    id: "eggs",
    name: "Eggs",
    nameTe: "గుడ్లు",
    slug: "eggs",
    description: "Fresh white & brown eggs — packs and trays from local farms.",
    image: IMG.whiteEggs,
  },
  {
    id: "fish",
    name: "Freshwater Fish",
    nameTe: "చేప",
    slug: "fish",
    description: "Rohu & katla — cleaned or cut the way you like.",
    image: IMG.fish,
  },
  {
    id: "prawns",
    name: "Prawns",
    nameTe: "రొయ్యలు",
    slug: "prawns",
    description: "Fresh prawns — cleaned or with shell.",
    image: IMG.prawns,
  },
];

export const products: Product[] = [
  // Goat — all cuts ₹999/kg
  {
    id: "goat-curry",
    slug: "goat-curry-cut",
    name: "Male Goat — Curry Cut",
    categoryId: "goat",
    cut: "Curry cut",
    description:
      "Bone-in curry pieces from live male goat. Ideal for Hyderabadi dum & home-style curries. Cut fresh after you order.",
    pricePerKg: 999,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.goat,
    featured: true,
    tags: ["Live-cut", "Bone-in"],
  },
  {
    id: "goat-biryani",
    slug: "goat-biryani-cut",
    name: "Male Goat — Biryani Cut",
    categoryId: "goat",
    cut: "Biryani cut",
    description:
      "Larger bone-in chunks sized for dum biryani. Fat trimmed to your preference at the shop.",
    pricePerKg: 999,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.goat,
    featured: true,
    tags: ["Live-cut", "Biryani"],
  },
  {
    id: "goat-boneless",
    slug: "goat-boneless",
    name: "Male Goat — Boneless",
    categoryId: "goat",
    cut: "Boneless",
    description:
      "Clean boneless goat meat for fry, gravy or kebab. Cut from the same live animal you select.",
    pricePerKg: 999,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.goat,
    tags: ["Boneless"],
  },
  {
    id: "goat-keema",
    slug: "goat-keema",
    name: "Male Goat — Keema",
    categoryId: "goat",
    cut: "Keema",
    description:
      "Freshly minced goat keema. No frozen mince — ground after cutting at the shop.",
    pricePerKg: 999,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.goat,
    tags: ["Minced"],
  },
  {
    id: "goat-paya",
    slug: "goat-paya",
    name: "Male Goat — Paya",
    categoryId: "goat",
    cut: "Paya",
    description:
      "Goat trotters cleaned and ready for slow-cooked paya. Available while stock lasts each morning.",
    pricePerKg: 999,
    unit: "kg",
    minQty: 0.5,
    step: 0.5,
    image: IMG.goat,
    tags: ["Specialty"],
  },
  // Sheep — all cuts ₹900/kg
  {
    id: "sheep-curry",
    slug: "sheep-curry-cut",
    name: "Male Sheep — Curry Cut",
    categoryId: "sheep",
    cut: "Curry cut",
    description:
      "Live-cut male sheep (mutton) curry pieces. Milder flavour than goat, perfect for everyday curries.",
    pricePerKg: 900,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.sheep,
    featured: true,
    tags: ["Live-cut"],
  },
  {
    id: "sheep-biryani",
    slug: "sheep-biryani-cut",
    name: "Male Sheep — Biryani Cut",
    categoryId: "sheep",
    cut: "Biryani cut",
    description:
      "Mutton biryani cut with the right bone-to-meat ratio for dum pots.",
    pricePerKg: 900,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.sheep,
    tags: ["Biryani"],
  },
  {
    id: "sheep-boneless",
    slug: "sheep-boneless",
    name: "Male Sheep — Boneless",
    categoryId: "sheep",
    cut: "Boneless",
    description: "Boneless mutton for fry, stew or seekh. Cut to order.",
    pricePerKg: 900,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.sheep,
  },
  {
    id: "sheep-keema",
    slug: "sheep-keema",
    name: "Male Sheep — Keema",
    categoryId: "sheep",
    cut: "Keema",
    description: "Fresh sheep keema, minced at the counter after live cut.",
    pricePerKg: 900,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.sheep,
  },
  {
    id: "sheep-paya",
    slug: "sheep-paya",
    name: "Male Sheep — Paya",
    categoryId: "sheep",
    cut: "Paya",
    description: "Sheep paya cleaned and packed for weekend nihari or soup.",
    pricePerKg: 900,
    unit: "kg",
    minQty: 0.5,
    step: 0.5,
    image: IMG.sheep,
  },
  // Broiler chicken — all ₹250/kg
  {
    id: "chicken-curry",
    slug: "chicken-curry-cut",
    name: "Broiler Chicken — Curry Cut",
    categoryId: "chicken",
    cut: "Curry cut",
    description:
      "White broiler (40–60 day birds). Curry cut with skin as preferred. Never frozen stock.",
    pricePerKg: 250,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.chicken,
    featured: true,
    tags: ["Daily fresh"],
  },
  {
    id: "chicken-boneless",
    slug: "chicken-boneless",
    name: "Broiler Chicken — Boneless",
    categoryId: "chicken",
    cut: "Boneless",
    description:
      "Boneless chicken breast & thigh for grill, curry or meal prep.",
    pricePerKg: 250,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.chicken,
  },
  {
    id: "chicken-whole",
    slug: "chicken-whole",
    name: "Broiler Chicken — Whole",
    categoryId: "chicken",
    cut: "Whole",
    description:
      "Whole cleaned broiler. Tell us if you want skin-on or skinless dressing.",
    pricePerKg: 250,
    unit: "kg",
    minQty: 1,
    step: 0.5,
    image: IMG.countryChicken,
  },
  // Country chicken — all ₹400/kg
  {
    id: "country-curry",
    slug: "country-chicken-curry-cut",
    name: "Country Chicken — Curry Cut",
    categoryId: "country-chicken",
    cut: "Curry cut",
    description:
      "Brown / country chicken (natu kodi). Firmer meat, deeper flavour — best slow-cooked.",
    pricePerKg: 400,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.countryChicken,
    featured: true,
    tags: ["Natu kodi"],
  },
  {
    id: "country-whole",
    slug: "country-chicken-whole",
    name: "Country Chicken — Whole",
    categoryId: "country-chicken",
    cut: "Whole",
    description: "Whole country bird, cleaned and ready for pot or roast.",
    pricePerKg: 400,
    unit: "kg",
    minQty: 1,
    step: 0.5,
    image: IMG.countryWhole,
  },
  // Eggs — white and brown clearly split
  {
    id: "eggs-white-6",
    slug: "white-eggs-6",
    name: "White Eggs (6 pcs)",
    categoryId: "eggs",
    cut: "White pack",
    description: "Farm-fresh white eggs, packed as a 6-piece pack.",
    pricePerKg: 30,
    unit: "piece",
    minQty: 1,
    step: 1,
    image: IMG.whiteEggs,
    featured: true,
    tags: ["White"],
  },
  {
    id: "eggs-white",
    slug: "eggs-white-tray",
    name: "White Eggs Tray (30)",
    categoryId: "eggs",
    cut: "White tray",
    description: "Farm-fresh white eggs, packed in a 30-egg tray.",
    pricePerKg: 210,
    unit: "tray",
    minQty: 1,
    step: 1,
    image: IMG.whiteEggs,
    tags: ["White"],
  },
  {
    id: "eggs-brown",
    slug: "eggs-brown-tray",
    name: "Brown Eggs Tray (30)",
    categoryId: "eggs",
    cut: "Brown tray",
    description: "Brown eggs from free-range style farms. Richer yolk colour.",
    pricePerKg: 300,
    unit: "tray",
    minQty: 1,
    step: 1,
    image: IMG.brownEggs,
    tags: ["Brown"],
  },
  // Fish — all ₹280/kg
  {
    id: "fish-rohu-clean",
    slug: "rohu-cleaned",
    name: "Rohu — Cleaned",
    categoryId: "fish",
    cut: "Cleaned",
    description:
      "Freshwater rohu, gutted and cleaned. Ask for curry pieces or fry cuts.",
    pricePerKg: 280,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.fish,
    featured: true,
    tags: ["Freshwater"],
  },
  {
    id: "fish-rohu-cut",
    slug: "rohu-cut",
    name: "Rohu — Cut Pieces",
    categoryId: "fish",
    cut: "Cut",
    description: "Rohu cut into curry-ready pieces. Bones left in for flavour.",
    pricePerKg: 280,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.fish,
  },
  {
    id: "fish-katla-clean",
    slug: "katla-cleaned",
    name: "Katla — Cleaned",
    categoryId: "fish",
    cut: "Cleaned",
    description: "Katla cleaned and ready. Popular for Andhra-style fish curry.",
    pricePerKg: 280,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.fish,
  },
  {
    id: "fish-katla-cut",
    slug: "katla-cut",
    name: "Katla — Cut Pieces",
    categoryId: "fish",
    cut: "Cut",
    description: "Katla cut to size for fry or gravy.",
    pricePerKg: 280,
    unit: "kg",
    minQty: 0.5,
    step: 0.25,
    image: IMG.fish,
  },
  // Prawns — all ₹320/kg
  {
    id: "prawns-cleaned",
    slug: "prawns-cleaned",
    name: "Prawns — Cleaned",
    categoryId: "prawns",
    cut: "Cleaned",
    description:
      "Deveined cleaned prawns. Ready for fry, gravy or biryani layering.",
    pricePerKg: 320,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.prawns,
    featured: true,
    tags: ["Cleaned"],
  },
  {
    id: "prawns-shell",
    slug: "prawns-with-shell",
    name: "Prawns — With Shell",
    categoryId: "prawns",
    cut: "With shell",
    description: "Whole prawns with shell. Better for spicy fry and gravy stock.",
    pricePerKg: 320,
    unit: "kg",
    minQty: 0.25,
    step: 0.25,
    image: IMG.prawns,
  },
];

export const stores: Store[] = [
  {
    id: "madhapur",
    name: "Thaaza Madhapur",
    area: "Madhapur",
    address: "Near Ayyappa Society, Madhapur, Hyderabad 500081",
    phone: "+91 90000 11111",
    hours: "6:30 AM – 9:30 PM",
    lat: 17.4484,
    lng: 78.3908,
    image: IMG.storeMadhapur,
    specialties: ["Goat & sheep live-cut", "Biryani cuts", "Same-day delivery"],
  },
  {
    id: "kukatpally",
    name: "Thaaza Kukatpally",
    area: "Kukatpally",
    address: "KPHB Main Road, Kukatpally, Hyderabad 500072",
    phone: "+91 90000 22222",
    hours: "6:30 AM – 9:30 PM",
    lat: 17.4948,
    lng: 78.3996,
    image: IMG.storeKukatpally,
    specialties: ["Country chicken", "Fish & prawns", "Morning stock"],
  },
  {
    id: "lb-nagar",
    name: "Thaaza LB Nagar",
    area: "LB Nagar",
    address: "Near Ring Road, LB Nagar, Hyderabad 500074",
    phone: "+91 90000 33333",
    hours: "6:30 AM – 9:00 PM",
    lat: 17.3457,
    lng: 78.5522,
    image: IMG.storeLbNagar,
    specialties: ["Family packs", "Egg trays", "Takeaway rush hours"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sravanthi R.",
    area: "Madhapur",
    text: "Finally a shop where I can see the animal before they cut. Biryani cut for Sunday dum is consistent — no surprises like frozen packets.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Mohammed Irfan",
    area: "Tolichowki",
    text: "Ordered goat keema for evening. They minced after cutting, packed properly, and delivery reached before Maghrib. Proper Hyderabad style.",
    rating: 5,
  },
  {
    id: "t3",
    name: "Lakshmi Devi",
    area: "Kukatpally",
    text: "Natu kodi curry cut was fresh — not the soft freezer chicken. My mother-in-law noticed the difference immediately.",
    rating: 5,
  },
  {
    id: "t4",
    name: "Pradeep Kumar",
    area: "LB Nagar",
    text: "Visit shop mode is useful. I pick the bird, they cut while I wait. Bill has GST breakup — clear and professional.",
    rating: 4,
  },
];

export const DELIVERY_FEE = 49;
export const GST_RATE = 0.05; // 5% demo GST on meat/fish for bill display
export const FREE_DELIVERY_ABOVE = 999;

export function getCategory(slug: string) {
  return categories.find((c) => c.slug === slug || c.id === slug);
}

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug || p.id === slug);
}

export function getStore(id: string) {
  return stores.find((s) => s.id === id);
}

export function getProductsByCategory(categoryId: string) {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}
